export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCSESS = "ALL_PRODUCT_SUCCSESS"
export const ALL_PRODUCT_FAILED = "ALL_PRODUCT_FAILED"


export const CLEAR_ERRORS = "CLEAR_ERRORS"
